---

oculus touch:
  button 0: A Press
  button 1: B Press
  button 2: X Press
  button 3: Y Press
  button 7: Start
  button 10: A Touch
  button 11: B Touch
  button 12: X Touch
  button 13: Y Touch
  button 8: Left Stick Press
  button 9: Right Stick Press
  button 16: Left Stick Touch
  button 17: Right Stick Touch
  button 18: Left Thumb Touch
  button 19: Right Thumb Touch
  button 14: Left Trigger Touch
  button 15: Right Trigger Touch
  axis 1: Left Stick Horizontal
  axis 2: Left Stick Vertical
  axis 4: Right Stick Horizontal
  axis 5: Right Stick Vertical
  axis 9: Left Trigger Press
  axis 10: Right Trigger Press
  axis 11: Left Grip Press
  axis 12: Right Grip Press

xbox one controller:
  left stick: { x: x axis, y: y axis }
  right stick: { x: 4th, y: 5th axis }
  d-pad: { x: 6th axis, y: 7th axis }
  triggers: { l: 9th axis, r: 10th axis }
  a: joystick button 0
  b: joystick button 1
  x: joystick button 2
  y: joystick button 3
  lb: joystick button 4
  rb: joystick button 5
  back: joystick button 6
  start: joystick button 7
  left stick: joystick button 8
  right stick: joystick button 9

...
